---
- name: ensure app profiles
  template:
    src: app.profile
    dest: "/etc/ufw/applications.d/{{ item.name | lower }}"
  loop: isset_ufw_applications

- name: ensure ufw rules
  ufw:
    rule: "{{ item.rule }}"
    proto: "{{ item.proto | default(isset_ufw_default_protocol) }}"
    name: "{{ item.name | default(omit) }}"
    src: "{{ item.src | default(omit) }}"
  loop: isset_ufw_rules

- name: ensure firewall state
  ufw:
    state: "{{ isset_ufw_firewall_state }}"