---
- name: ensure app profiles
  template:
    src: app.profile
    dest: "/etc/ufw/applications.d/{{ item.name | lower }}"
  loop: "{{ isset_ufw_applications }}"

- name: ensure inbound ufw app rules
  ufw:
    rule: allow
    app: "{{ source.0.name }}"
    src: "{{ source.1 }}"
  loop: "{{ isset_ufw_applications | subelements('sources') | default([]) }}"
  loop_control:
    loop_var: source
  when:
    - source is iterable
    - source.0 is mapping
    - source.0 is defined

- name: ensure outbound ufw app rules
  ufw:
    rule: allow
    app: "{{ target.0.name }}"
    to: "{{ target.1 }}"
  loop: "{{ isset_ufw_applications | subelements('targets') | default([]) }}"
  loop_control:
    loop_var: target
  when:
    - target is iterable
    - target.0 is mapping
    - target.0 is defined

- name: ensure ufw rules
  ufw:
    rule: "{{ item.rule }}"
    proto: "{{ item.proto | default(omit) }}"
    app: "{{ item.app | default(omit) }}"
    src: "{{ item.src | default(omit) }}"
  loop: "{{ isset_ufw_rules }}"

- name: ensure logging status
  ufw:
    log: "{{ isset_ufw_log }}"

- name: ensure default inbound
  ufw:
    direction: incoming
    policy: "{{ isset_ufw_inbound_default }}"

- name: ensure default outbound
  ufw:
    direction: outgoing
    policy: "{{ isset_ufw_outbound_default }}"

- name: ensure firewall state
  ufw:
    state: "{{ isset_ufw_firewall_state }}"