---
- name: ensure app profiles
  template:
    src: app.profile
    dest: "/etc/ufw/applications.d/{{ item.name | lower }}"
  loop: "{{ isset_ufw_applications }}"

- name: ensure ufw app rules
  ufw:
    rule: allow
    app: "{{ item.0.name }}"
    src: "{{ item.1 }}"
  with_subelements:
    - "{{ isset_ufw_applications }}"
    - sources
# Notify 'ufw app reload app?'

- name: ensure ufw rules
  ufw:
    rule: "{{ item.rule }}"
    proto: "{{ item.proto | default(omit) }}"
    app: "{{ item.app | default(omit) }}"
    src: "{{ item.src | default(omit) }}"
  loop: "{{ isset_ufw_rules }}"

- name: ensure firewall state
  ufw:
    state: "{{ isset_ufw_firewall_state }}"